### ISSUE TITLE
Feature: Add ability to switch VPN providers

### ISSUE THREAD

**Issue by RonanCodes** [invizbox/invizbox-2#4]
We should be able to switch from NordVPN to ProtonVPN for example.

**Comment by gitnewcomer** [comment]
> We should be able to switch from NordVPN to ProtonVPN for example.

It isn't complicated to do it yourself if you look carefully in the source code... :)

**Comment by invizbox** [comment]
This repository is VPN provider agnostic which means that you are welcome to set it up with the VPN provider of your choice. The ability to switch from one provider to another is not relevant to this code. It is also not a feature for the released code. There is an official statement here: https://support.invizbox.com/hc/en-us/articles/360007644997-Can-I-switch-VPN-providers-on-my-InvizBox-2-

That said, as mentioned by @gitnewcomer, the source code for all versions is here.
